### ISSUE TITLE
Some functions get called twice

### ISSUE THREAD

**Issue by joshrotenberg** [daggerok/generator-jvm#28]
I think this group (and the following group) of functions will get called twice because of the way yeoman automatically calls methods even if they aren't part of the core (writing, initializing, etc). I think they should either be declared private (i.e. `_privateCopyCommons()`) or not called explicitly here as they'll be called later on in processing.

I'm brand new to yeoman, though, so please close this if I'm missing something.

**Comment by daggerok** [comment]
Hello @joshrotenberg ,

> because of the way yeoman automatically calls methods even if they aren't part of the core (writing, initializing, etc). I think they should either be declared private

Can you please send me a link where you read about that? Thanks!

**Comment by joshrotenberg** [comment]
Sure! 

On https://yeoman.io/authoring/running-context.html ...

> Each method directly attached to a Generator prototype is considered to be a task. Each task is run in sequence by the Yeoman environment run loop.

Specifically, in the example:

```
class extends Generator {
    // method1 will run just between configuring() and default() 
     method1() {
       console.log('hey 1');
     }

     _private_method() {
       console.log('private hey');
     }
   }
```

Honestly this completely confused me at first as well (I'm writing my own generator and was looking around for examples to figure out what was going on).

**Comment by daggerok** [comment]
Well, good to know and thanks that pointing me into this, I didn't even know it.
If I will have time, maybe this weekend I will fix my generator together with other few mistakes it contains.
Why it's working in my case? It's only because I have used functional approach with less possible state, so even after couple of executions result was pretty match same.

Thanks!

**Comment by daggerok** [comment]
fixed: https://github.com/daggerok/generator-jvm/pull/30
